name: Metricon CI

on:
  push:
    branches: [main]

jobs:
  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - run: npm install

      - run: npm run build

  rust-check:
    name: Rust Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: programs/metricon_vault/src

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo check
